export const options: { label: string; checkBoxOptions: string[] }[] = [
  {
    label: "Daily Touchpoints",
    checkBoxOptions: [
      "ATM",
      "Convenience store",
      "Department store",
      "Grocery or Supermarket",
      "Post Office",
      "Store",
    ],
  },
  {
    label: "Entertainment",
    checkBoxOptions: [
      "Bar",
      "Liquor store",
      "Movie rental",
      "Movie theatre",
      "Night club",
      "Park",
    ],
  },
  {
    label: "Travel",
    checkBoxOptions: [
      "Airport",
      "Bus station",
      "Gas station",
      "Lodging",
      "Parking",
      "Subway station",
      "Taxi stand",
      "Train station",
    ],
  },
  {
    label: "Food",
    checkBoxOptions: [
      "Bakery",
      "Cafe",
      "Food",
      "Meal delivery",
      "Meal takeaway",
      "Restaurant",
    ],
  },
  {
    label: "Shopping",
    checkBoxOptions: ["Shopping mall", "Clothing store", "Electronics store"],
  },
  {
    label: "Education",
    checkBoxOptions: ["Book store", "Library", "School", "Unviersity"],
  },
  {
    label: "Health",
    checkBoxOptions: [
      "Dentist",
      "Doctor",
      "Gym",
      "Health",
      "Hospital",
      "Pharmacy",
      "Physiotherapist",
    ],
  },
  {
    label: "Home Services",
    checkBoxOptions: [
      "Electrtician",
      "Furniture store",
      "General contractor",
      "Hardware store",
      "Home goods store",
      "Laundry",
      "Painter",
      "Plumber",
      "Roofing contractor",
    ],
  },
  {
    label: "Lifestyle",
    checkBoxOptions: ["Beauty salon", "Hair care", "Jewelry store", "Spa"],
  },
  {
    label: "Business",
    checkBoxOptions: [
      "Accounting",
      "Bank",
      "Establisment",
      "Finance",
      "Insurance ageny",
      "Lawyer",
    ],
  },
  {
    label: "Tourism",
    checkBoxOptions: [
      "Amusement park",
      "Aquarium",
      "Art gallery",
      "Car rental",
      "Museum",
      "Travel agency",
      "Zoo",
    ],
  },
  {
    label: "Religious",
    checkBoxOptions: [
      "Church",
      "Hindu temple",
      "Mosque",
      "Place of worship",
      "Synagogue",
    ],
  },
  {
    label: "Others",
    checkBoxOptions: [
      "Car dealer",
      "Car repair",
      "Fire station",
      "Local government office",
      "Pet store",
      "Police",
      "Real estate agency",
      "Shoe store",
      "Stadium",
      "Veterinary Care",
    ],
  },
  {
    label: "Daily Touchpoints",
    checkBoxOptions: [
      "ATM",
      "Convenience store",
      "Department store",
      "Grocery or Supermarket",
      "Post Office",
      "Store",
    ],
  },
  {
    label: "Entertainment",
    checkBoxOptions: [
      "Bar",
      "Liquor store",
      "Movie rental",
      "Movie theatre",
      "Night club",
      "Park",
    ],
  },
  {
    label: "Travel",
    checkBoxOptions: [
      "Airport",
      "Bus station",
      "Gas station",
      "Lodging",
      "Parking",
      "Subway station",
      "Taxi stand",
      "Train station",
    ],
  },
  {
    label: "Food",
    checkBoxOptions: [
      "Bakery",
      "Cafe",
      "Food",
      "Meal delivery",
      "Meal takeaway",
      "Restaurant",
    ],
  },
  {
    label: "Shopping",
    checkBoxOptions: ["Shopping mall", "Clothing store", "Electronics store"],
  },
  {
    label: "Education",
    checkBoxOptions: ["Book store", "Library", "School", "Unviersity"],
  },
  {
    label: "Health",
    checkBoxOptions: [
      "Dentist",
      "Doctor",
      "Gym",
      "Health",
      "Hospital",
      "Pharmacy",
      "Physiotherapist",
    ],
  },
  {
    label: "Home Services",
    checkBoxOptions: [
      "Electrtician",
      "Furniture store",
      "General contractor",
      "Hardware store",
      "Home goods store",
      "Laundry",
      "Painter",
      "Plumber",
      "Roofing contractor",
    ],
  },
  {
    label: "Lifestyle",
    checkBoxOptions: ["Beauty salon", "Hair care", "Jewelry store", "Spa"],
  },
  {
    label: "Business",
    checkBoxOptions: [
      "Accounting",
      "Bank",
      "Establisment",
      "Finance",
      "Insurance ageny",
      "Lawyer",
    ],
  },
  {
    label: "Tourism",
    checkBoxOptions: [
      "Amusement park",
      "Aquarium",
      "Art gallery",
      "Car rental",
      "Museum",
      "Travel agency",
      "Zoo",
    ],
  },
  {
    label: "Religious",
    checkBoxOptions: [
      "Church",
      "Hindu temple",
      "Mosque",
      "Place of worship",
      "Synagogue",
    ],
  },
  {
    label: "Others",
    checkBoxOptions: [
      "Car dealer",
      "Car repair",
      "Fire station",
      "Local government office",
      "Pet store",
      "Police",
      "Real estate agency",
      "Shoe store",
      "Stadium",
      "Veterinary Care",
    ],
  },
];
