export const icons = {
  mic: '/assets/images/mic.png',
  searchone: '/assets/images/mobilesearch.png',
  searchhoarding: '/assets/images/searchhoarding.png',
  searchlocation: '/assets/images/searchlocation.png',
  searchcalender: '/assets/images/searchcalender.png',
  searchmobilemic: '/assets/images/searchmobilemic.png',
  searchmobileicon: '/assets/images/mobilesearch.png',
  dealone: '/assets/images/dealone.png',
  dealtwo: '/assets/images/dealtwo.png',
  dealthree: '/assets/images/dealthree.png',
  dealfour: '/assets/images/dealfour.png',
  color: '/assets/images/colors.png',
  zee: '/assets/images/zee.png',
  tensports: '/assets/images/tensports.png',
  star: '/assets/images/star.png',
  privateone: '/assets/images/privateone.png',
  privatetwo: '/assets/images/privatetwo.png',
  privatethree: '/assets/images/privatethree.png',
  privatefour: '/assets/images/privatefour.png',
  privatearrowleft: '/assets/images/privateleftarrow.png',
  privatearrowright: '/assets/images/privaterightarrow.png',
  dot: '/assets/images/dots.png',
  logo: '/assets/images/logo.png',
  logomobile: '/assets/images/logomobile.png',
  logotwo: '/assets/images/logotwo.png',
  logotwomobile: '/assets/images/logotwomobile.png',
  user: '/assets/images/user.png',
  bag: '/assets/images/bag.png',
  globe: '/assets/images/globe.png',
  heart: '/assets/images/heart.png',
  menu: '/assets/images/menu.png',
  leftbtnarrow: '/assets/images/leftbtnarrow.png',
  rightbtnarrow: '/assets/images/rightbtnarrow.png',
  bottomarrow: '/assets/images/bottomarrow.png',
  textboxsearch: '/assets/images/Search.png',
  expert: '/assets/images/expert.svg',
  franchisee: '/assets/images/franchisee.svg',
  services: '/assets/images/services.svg',
  credit: '/assets/images/credit.svg',
  insurance: '/assets/images/insurance.svg',
  barcode:'/assets/images/barcode.svg',
  amb_spesh : '/assets/images/amb_spesh.svg',
  samsung : '/assets/svg/samsung.svg',
  bmw: '/assets/svg/bmw.svg',
  instagram: '/assets/svg/insta.svg',
  audi: '/assets/svg/audi.svg',
  redbull: '/assets/svg/redbull.svg',
  disney: '/assets/svg/disney.svg',
  tiktok: '/assets/svg/tiktok.svg',
  nivea: '/assets/svg/nivea.svg',
  emirates: '/assets/svg/emirates.svg',
  netflix: '/assets/svg/netflix.svg',
  amazon: '/assets/svg/amazon.svg',
  philips: '/assets/svg/philips.svg',
  close:'/assets/images/close.png',
  setting:'/assets/images/setting.png',
  uparrow:'/assets/images/uparrow.png',
  reload:'/assets/images/reload.png',
  sort:'/assets/images/sort.png',
  leftarrow:'/assets/images/leftarrow.png',
  paymentStrip:'/assets/images/paymentstrip.png',
  twitter:"/assets/svg/twitter.svg",
  facebook:"/assets/svg/facebook.svg",
  youtube:"/assets/svg/youtube.svg",
  linkedIn:"/assets/svg/linkedin.svg",
  medium:"/assets/svg/medium.svg",
  plus:"/assets/svg/plus.svg",
  followTick:"/assets/svg/followTick.svg",
 
};

export const svgs = {
  appstore: `/assets/svg/appstore.svg`,
  americanexpress: `/assets/svg/americanexpress.svg`,
  bag: `/assets/svg/bag.svg`,
  bharatqr: `/assets/svg/bharatqr.svg`,
  bitcoin: `/assets/svg/bitcoin.svg`,
  cheque: ` /assets/svg/cheque.svg`,
  calender: `/assets/svg/calender.svg`,
  calendarGray:`/assets/svg/calendarGray.svg`,
  calendarPink:`/assets/svg/calendarPink.svg`,
  cross: `/assets/svg/cross.svg`,
  downarrow: `/assets/svg/downarrow.svg`,
  easyemioption: `/assets/svg/easyemioption.svg`,
  easyloanoption: `/assets/svg/easyloanoption.svg`,
  globe: `/assets/svg/globe.svg`,
  googleplay: `/assets/svg/googleplay.svg`,
  homesearchicon: `/assets/svg/homesearchicon.svg`,
  homesearchlocation: `/assets/svg/homelocation.svg`,
  imps: `/assets/svg/imps.svg`,
  interact:`/assets/svg/send-2.svg`,
  lightrightarrow: `/assets/svg/lightrightarrow.svg`,
  like:`/assets/svg/like.svg`,
  maestro: `/assets/svg/maestro.svg`,
  master: `/assets/svg/master.svg`,
  menu: `/assets/svg/menu.svg`,
  mic: `/assets/svg/mic.svg`,
  micPink:`/assets/svg/micPink.svg`,
  mouse: `/assets/svg/mouse.svg`,
  mousedownarrow: `/assets/svg/mousedownarrow.svg`,
  neftrtgs: `/assets/svg/neftrtgs.svg`,
  netbanking: `/assets/svg/netbanking.svg`,
  ninedots: `/assets/svg/ninedots.svg`,
  ninedotsdummy: `/assets/svg/ninedotsdummy.svg`,
  paypal: `/assets/svg/paypal.svg`,
  paymentStrip:'/assets/svg/paymentstrip.svg',
  privatebtnarrow: `/assets/svg/privatebtnarrow.svg`,
  profilelogo: `/assets/svg/profilelogo.svg`,
  rupay: `/assets/svg/rupay.svg`,
  repost:`/assets/svg/redo.svg`,
  shortlist: `/assets/svg/shortlist.svg`,
  scrollarrow: `/assets/svg/scrollarrow.svg`,
  sliderbtnarrow: `/assets/svg/sliderbtnarrow.svg`,
  upi: `/assets/svg/upi.svg`,
  visa: `/assets/svg/visa.svg`,
  wallet: `/assets/svg/wallet.svg`,
  weblogo: `/assets/svg/web_logo.svg`,
  weblogotwo: `/assets/svg/web_logo_two.svg`,
  adicon: `/assets/svg/adicon.svg`,
  transporticon: `/assets/svg/transporticon.svg`,
  buildingicon: `/assets/svg/buildingicon.svg`,
  hoardingicon: `/assets/svg/hoardingicon.svg`,
  listicon: `/assets/svg/listicon.svg`,
  care: `/assets/svg/care.svg`,
  client: `/assets/svg/client.svg`,
  conversation: `/assets/svg/conversation.svg`,
  analytics: `/assets/svg/analytics.svg`,
  contract: `/assets/svg/contract.svg`,
  creditcard: `/assets/svg/credit_card.svg`,
  money: `/assets/svg/money.svg`,
  wallettwo: `/assets/svg/wallettwo.svg`,
  searchHoarding: `/assets/svg/searchhoarding.svg`,
  postPhoto:`/assets/svg/gallery.svg`,
  postVideo:`/assets/svg/video-play.svg`,
  postEvent:`/assets/svg/menu-board.svg`,
  privateHoarding: `/assets/svg/private_hoarding.svg`,
  privateDigiad: `/assets/svg/private_digiad.svg`,
  privateMobi: `/assets/svg/private_mobi.svg`,
  privatePaper: `/assets/svg/private_paper.svg`,
  demo:'/assets/svg/demo.svg',
  demotwo:'/assets/svg/demotwo.svg',
  user_experience : '/assets/svg/user_experience.svg',
  customer_service : '/assets/svg/customer_service.svg',
  improvement : '/assets/svg/improvement.svg',
  ecommerce : '/assets/svg/ecommerce.svg',
  review: '/assets/svg/review.svg',
  brandone: '/assets/svg/brandone.svg',
  brandtwo: '/assets/svg/brandtwo.svg',
  brandthree: '/assets/svg/brandthree.svg',
  brandfour: '/assets/svg/brandfour.svg',
  brandfive: '/assets/svg/brandfive.svg',
  brandsix: '/assets/svg/brandsix.svg',
  circlearrow: '/assets/svg/circlearrow.svg',
  more: '/assets/svg/more.svg',
  save:`/assets/svg/archive-tick.svg`,
  book:`/assets/svg/book.svg`,
  arrowChevron:`/assets/svg/arrowChevron.svg`,
  shareIcon:"/assets/svg/shareIcon.svg",
  shotsSave:"/assets/svg/shotSave.svg",
  arrowPinkRight:"/assets/svg/Arrow - Right.svg",
  sharePost:"/assets/svg/share-2.svg",
  copyPost:"/assets/svg/copy.svg",
  embedPost:"/assets/svg/embedPost.svg",
  hidePost:"/assets/svg/hidePost.svg",
  reportPost:"/assets/svg/reportPost.svg",
  improvePost:"/assets/svg/improvePost.svg",
  elipse:"/assets/svg/elipse.svg"
  
};

export const customPng = {
  kisspng:"/assets/images/kisspng-google.png",
}
export const customSvg ={
  illustration1: "/assets/svg/illustration1.svg",
  illustration2: "/assets/svg/illustration2.svg",
  illustration3: "/assets/svg/illustration3.svg"
}